config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :employees
  root 'manage#index'
  resources :manage
  delete 'manage/:id/destroy' => 'manage#destroy'
  get 'manage/:id/arrival_report' => 'manage#arrival_report'
  get 'manage/arrival_report/:id/section' => 'manage#arrival_report_section'
  get 'manage/:id/working_time' => 'manage#working_time'
  get 'manage/:id/working_time/section' => 'manage#working_time_section'
  get 'manage/:id/not_worked_days' => 'manage#not_worked_days'
  get 'manage/:id/not_worked_days/section' => 'manage#not_worked_days_section'
  get 'manage/:id/add_entry_time' => 'manage#add_entry_time'
  post 'manage/save_entry' => 'manage#save_entry'
  get 'employee/' => 'employee#index'
  get 'employee/profile' => 'employee#profile'
  get 'home/' => 'home#index'
  get 'home/unauthorized' => 'home#unauthorized'
  namespace :api do
    resources :control
  end
end

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%=root_path%>">Textile.Co</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="/manage">Manage Employees</a></li>
        <li><%= link_to 'Log in', '' %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= "#{session[:employee_first_name]} #{session[:employee_last_name]}" %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Profile</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Log out', '', method: 'delete' %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "CustomerProjectV2" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "general" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%=link_to "Textile.Co",root_path, class: "navbar-brand"%>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Manage Employees", "/path1"  %></li>
            <li><%= link_to "Arrival Report", "/path2"  %></li>
            <li><%= link_to "Working Time", "/path3"  %></li>
          </ul>
          <% if employee_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%="#{current_employee.first_name} #{current_employee.last_name}" %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Profile</a></li>
                  <li><a href="#">Change Password</a></li>
                  <li role="separator" class="divider"></li>
                  <li><%=link_to "Logout", destroy_employee_session_path, method: "delete" %></li>
                </ul>
              </li>
          </ul>
        <% end %>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
          <%= bootstrap_flash %>
          <%= yield %>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>